<div class="brushes">
    <div class="brushes-container">
        <div class="brushes-text">
            <h3 class="title">Find the right brush for your Philips Sonicare toothbrush</h3>
            <p class="text">Choose your Sonicare toothbrush to see all compatible brush heads</p>
        </div>

        <div class="brushes-list">
            <?php foreach($brushes as $i => $brush) : ?>
                <div id="brush-<?php echo $brush->id ?>" class="brush <?php echo ($brush->preferred === 1) ? 'active' : ''; ?>" data-id="<?php echo $brush->id ?>">
                    <img class="brush-img" src="/content/images/handles/<?php echo $brush->image ?>.png" alt="" />
                    <img class="brush-img-blur" src="/content/images/handles/<?php echo $brush->image ?>-blur.png" alt="" />
                    <div class="brush-name"><?php echo $brush->name ?></div>
                </div>
            <?php endforeach; ?>
        </div>

        <button type="button" class="btn-prev icon icon-arrow-left"></button>
        <button type="button" class="btn-next icon icon-arrow-right"></button>

        <ol class="list-unstyled brush-indicators">
            <?php foreach($brushes as $i => $brush) : ?>
                <li data-id="brush-<?php echo $brush->id ?>" class="brush-indicator <?php echo ($brush->preferred === 1) ? 'active' : ''; ?>"></li>
            <?php endforeach; ?>
        </ol>
    </div>
</div>

<div class="brushheads">
    <div class="brushheads-container">
        <?php foreach($brushes as $brush_i => $brush) : ?>
            <div id="brushheads-<?php echo $brush->id ?>" class="brushhead-collection <?php echo ($brush->preferred === 1) ? 'active' : ''; ?>">

                <?php foreach($brush->compatibleBrushHeads as $brushHead_i => $brushhead) : ?>
                    <div data-id="<?php echo $brushhead->id ?>" class="brushhead <?php echo ($brushHead_i === 0) ? 'active' : ''; ?>">
                        <div class="brushhead-image">
                            <img src="/content/images/brushes/<?php echo $brushhead->image ?>" alt="" />
                        </div>

                        <?php if ($brushhead->isStandard) : ?>
                            <div class="brushhead-ribbon">standard</div>
                        <?php endif; ?>

                        <div class="brushhead-content">
                            <div class="name"><?php echo $brushhead->name ?></div>
                            <small class="key"><?php echo $brushhead->key ?></small>
                            <p class="description"><?php echo $brushhead->description ?></p>

                            <div class="brushhead-packs">
                                <?php foreach($brushhead->brushPacks as $brushPack_i => $brushPack) : ?>
                                    <button type="button" class="brushhead-pack-btn <?php echo ($brushHead_i === 0 && $brushPack_i === 0) ? 'active' : ''; ?>" data-id="<?php echo $brushPack->id ?>">
                                        <div class="brush-icon">
                                            <i class="icon icon-brush"></i>
                                            x
                                            <span class="brush-icon-count"><?php echo $brushPack->numBrushes ?></span>
                                        </div>
                                        <div class="numbrushes"><?php echo $brushPack->numBrushes ?> pack</div>
                                    </button>
                                <?php endforeach; ?>
                            </div>
                        </div>

                        <div class="brushpack-collection">
                            <div class="brushpack-arrow"></div>

                            <?php foreach($brushhead->brushPacks as $brushPack_i => $brushPack) : ?>
                                <div class="brushpack <?php echo ($brushHead_i === 0 && $brushPack_i === 0) ? 'active' : ''; ?>" data-id="<?php echo $brushPack->id ?>">
                                    <div class="numbrushes"><?php echo $brushPack->numBrushes ?> pack <?php echo $brushhead->name ?></div>
                                    <p>Subscribe your frequent delivery of your brushes at on of these retailers:</p>
                                    <div class="retailers">
                                        <?php foreach($brushPack->retailers as $retailer_i => $retailer) : ?>
                                            <a class="retailer" data-id="<?php echo $retailer->id ?>" href="<?php echo $brushPack->retailers_url[$retailer_i] ?>" target="_blank" rel="nofollow">
                                                <img src="/content/images/retailer/<?php echo $retailer->logo ?>" alt="" />
                                                <span class="name"><?php echo $retailer->name ?> ›</span>
                                            </a>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endforeach; ?>

            </div>
        <?php endforeach; ?>
    </div>
</div>
