<div class="education">
    <div class="education-container">
        <div class="education-image">
            <img src="/content/images/education.png" alt="" />
        </div>

        <div class="education-content">
            <h2>Brush heads subscription service</h2>
            <p>We want to make sure you get the most out of your Philips Sonicare toothbrush. In order to do so, it’s important to replace your brush every three months. A fresh brush maximizes the effectiveness of Philips’ unique Sonicare technology, so choose the right brush, subscribe and take advantage of the following benefits:</p>
            <ul>
                <li>No commitment</li>
                <li>Easy cancellation</li>
                <li>Easy to change delivery frequency</li>
                <li>Never run out</li>
            </ul>
        </div>
    </div>
</div>
