<footer class="footer">
    <div class="footer-row">
        <div class="footer-logo">
            <img src="http://www.philips.com/content/dam/corporate/philips-footer-logo.png" title="" alt="">
        </div>

        <div class="footer-share">
            <h3 class="footer-title">Blijf op de hoogte van Philips</h3>

            <a href="http://www.youtube.com/Philips" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_yt.png" title="" alt="">
            </a>

            <a href="http://twitter.com/PhilipsNL" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_tw.png" title="" alt="">
            </a>

            <a href="http://www.facebook.com/PhilipsNederland" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_fb.png" title="" alt="">
            </a>

            <a href="http://www.pinterest.com/philipsbenelux/" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_pr.png" title="" alt="">
            </a>

            <a href="http://www.instagram.com/PhilipsNL" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_ig.png" title="" alt="">
            </a>

            <a href="https://www.linkedin.com/company/3512986" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_li.png" title="" alt="">
            </a>
        </div>

    </div>

    <div class="footer-nav">
        <ul class="list-unstyled">
            <li>
                <a href="http://www.philips.com/about/investor/index.page">Investor Relations</a>
            </li>
            <li>
                <a href="http://www.careers.philips.com/nl_nl/index.wpd">Carrière</a>
            </li>
            <li>
                <a href="http://www.support.philips.com/support/contact/contact_page.jsp?userLanguage=nl&userCountry=nl">Contact opnemen met Philips</a>
            </li>
            <li>
                <a href="http://www.philips.nl/siteowner">Philips</a>
            </li>
            <li>
                <a href="http://www.philips.nl/privacypolicy">Privacybeleid</a>
            </li>
            <li>
                <a href="http://www.philips.nl/terms">Gebruiksvoorwaarden</a>
            </li>
            <li>
                <a href="http://www.sitemap.philips.com/sitemap/nl_nl/">Sitemap</a>
            </li>
        </ul>
    </div>

    <div class="footer-copyright">
        © Koninklijke Philips N.V., 2004 - 2014. Alle rechten voorbehouden.
    </div>
</footer>
