<footer class="footer">
    <div class="footer-row">
        <div class="footer-logo">
            <img src="http://www.philips.com/content/dam/corporate/philips-footer-logo.png" title="" alt="">
        </div>

        <div class="footer-share">
            <h3 class="footer-title">Blijf op de hoogte van Philips</h3>

            <a href="http://www.youtube.com/Philips" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_yt.png" title="" alt="">
            </a>

            <a href="http://twitter.com/PhilipsNL" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_tw.png" title="" alt="">
            </a>

            <a href="http://www.facebook.com/PhilipsNederland" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_fb.png" title="" alt="">
            </a>

            <a href="http://www.pinterest.com/philipsbenelux/" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_pr.png" title="" alt="">
            </a>

            <a href="http://www.instagram.com/PhilipsNL" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_ig.png" title="" alt="">
            </a>

            <a href="https://www.linkedin.com/company/3512986" target="_blank">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_li.png" title="" alt="">
            </a>
        </div>

        <div class="footer-links">
            <div class="footer-selectcountry">
                <a href="http://www.philips.com/global/country_selector.page?locale_org=nl_nl.L2NvbnRlbnQvY29tbW9uL25sX05ML2Nyc2MvY2hwLWZvb3Rlcg.html">
                    <span class="footer-selectcountry-label">Select country/language</span>
                    NL - Nederlands <i class="icon icon-arrow-right"></i>
                </a>
            </div>

            <div class="footer-selectsite">
                <h3 class="footer-title">
                    Selecteer site <span class="footer-title-sub">Philips - Nederland <i class="icon icon-arrow-bottom"></i></span>
                </h3>
                <ul class="footer-dropdown list-unstyled">
                    <li class="p-always-visible">
                        <a href="/c-m/consumenten-producten">Consumentenproducten</a>
                    </li>
                    <li>
                        <a href="http://www.healthcare.philips.com/nl_nl/">Gezondheidszorg</a>
                    </li>
                    <li>
                        <a href="http://www.lighting.philips.nl/">Licht</a>
                    </li>
                    <li class="p-always-visible">
                        <a href="http://www.philips.nl/about/company/index.page">Over Philips</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="footer-nav">
        <ul class="list-unstyled">
            <li>
                <a href="http://www.philips.com/about/investor/index.page">Investor Relations</a>
            </li>
            <li>
                <a href="http://www.careers.philips.com/nl_nl/index.wpd">Carrière</a>
            </li>
            <li>
                <a href="http://www.support.philips.com/support/contact/contact_page.jsp?userLanguage=nl&userCountry=nl">Contact opnemen met Philips</a>
            </li>
            <li>
                <a href="http://www.philips.nl/siteowner">Philips</a>
            </li>
            <li>
                <a href="http://www.philips.nl/privacypolicy">Privacybeleid</a>
            </li>
            <li>
                <a href="http://www.philips.nl/terms">Gebruiksvoorwaarden</a>
            </li>
            <li>
                <a href="http://www.sitemap.philips.com/sitemap/nl_nl/">Sitemap</a>
            </li>
        </ul>
    </div>

    <div class="footer-copyright">
        © Koninklijke Philips N.V., 2004 - 2014. Alle rechten voorbehouden.
    </div>
</footer>
