<footer class="footer">
    <div class="footer-row">
        <div class="footer-logo">
            <img src="http://www.philips.com/content/dam/corporate/philips-footer-logo.png" title="" alt="">
        </div>

        <div class="footer-share">
            <h3 class="footer-title">Connect with Philips</h3>

            <a href="http://www.youtube.com/Philips" target="_blank" data-name="youtube">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_yt.png" title="" alt="">
            </a>

            <a href="https://twitter.com/Philips" target="_blank" data-name="twitter">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_tw.png" title="" alt="">
            </a>

            <a href="http://www.facebook.com/Philips" target="_blank" data-name="facebook">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_fb.png" title="" alt="">
            </a>

            <a href="http://www.pinterest.com/philipsglobal/" target="_blank" data-name="pinterest">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_pr.png" title="" alt="">
            </a>

            <a href="https://plus.google.com/+Philips" target="_blank" data-name="google-plus">
                <img src="http://www.philips.com/content/dam/corporate/chp-footer/chp_footer_gp.png" title="" alt="">
            </a>
        </div>

    </div>

    <div class="footer-nav">
        <ul class="list-unstyled">
            <li>
                <a href="http://www.philips.com/about/investor/index.page">Investor Relations</a>
            </li>
            <li>
                <a href="http://www.usa.careers.philips.com/">Careers</a>
            </li>
            <li>
                <a href="http://www.support.philips.com/support/contact/contact_page.jsp?userLanguage=en&amp;userCountry=us">Contact</a>
            </li>
            <li>
                <a href="http://www.usa.philips.com/siteowner">Philips</a>
            </li>
            <li>
                <a href="http://www.usa.philips.com/privacypolicy">Privacy policy</a>
            </li>
            <li>
                <a href="http://www.usa.philips.com/terms">Terms of use</a>
            </li>
            <li>
                <a href="http://www.sitemap.philips.com/sitemap/us_en/">Site Map</a>
            </li>
            <li>
                <a href="https://www.facebook.com/philips">Facebook</a>
            </li>
            <li>
                <a href="http://www.twitter.com/philipscare_na">Twitter</a>
            </li>
        </ul>
    </div>

    <div class="footer-copyright">
        © Koninklijke Philips N.V., 2014. All rights reserved.
    </div>
</footer>
