<div class="n01-header">
    <header class="p-n01-header" data-comp-id="n01Header">
        <div class="p-shadow-overlay"></div>
        <div class="p-logo-wrapper">
            <img src="/content/images/logo.jpg" alt="" class="p-logo" />
        </div>
        <div class="p-topbar">
            <div class="p-bar-wrapper">
                <ul class="p-bar-nav">
                    <li class="p-sub-menu-single-column current">
                        <a href="/c-m/consumenten-producten" class="p-sub-menu-link">Oral Healthcare</a>
                    </li>
                    <li class="p-sub-menu-single-column">
                        <a href="http://www.philipsstore.nl/" class="p-sub-menu-link">The Philips<br />Sonicare Difference</a>
                    </li>
                    <li class="p-sub-menu-single-column">
                        <a href="/c-m/consumenten-ondersteuning" class="p-sub-menu-link">Toothbrushes</a>
                    </li>
                    <li class="p-sub-menu-single-column">
                        <a href="http://www.philips.nl/e/" class="p-sub-menu-link">Brush Heads</a>
                    </li>
                    <li class="p-sub-menu-single-column">
                        <a href="http://www.promotion.philips.com/nl/nl/" class="p-sub-menu-link">Regimen</a>
                    </li>
                </ul>

                <form class="p-search" action="http://www.philips.com/search/search">
                    <fieldset>
                        <input type="hidden" name="language" value="nl">
                        <input type="hidden" name="country" value="nl">
                        <input type="hidden" name="s" value="corporate">
                        <input type="hidden" name="sid" value="header">
                        <input type="text" name="q" autocomplete="off" placeholder="Wat zoek je&#x3f;">
                        <button type="submit"></button>
                    </fieldset>
                </form>

                <span class="p-small-nav"></span>
            </div>
        </div>

        <span class="p-left-bar"></span>

        <nav class="p-sidebar p-hidden">
            <div class="p-nav-wrapper">
                <div class="p-search-bar">
                    <form class="p-search" action="http://www.philips.com/search/search">
                        <fieldset>
                            <input type="hidden" name="language" value="nl">
                            <input type="hidden" name="country" value="nl">
                            <input type="hidden" name="s" value="corporate">
                            <input type="hidden" name="sid" value="header">
                            <input type="text" name="q" autocomplete="off" placeholder="Wat zoek je?">
                            <button type="submit"></button>
                        </fieldset>
                    </form>
                </div>

                <ul class="p-category-nav">
                    <li class="p-category-nav-item">
                        <a href="/c-m/consumenten-producten" class="p-category-nav-link">Oral Healthcare</a>
                    </li>
                    <li class="p-category-nav-item">
                        <a href="http://www.philipsstore.nl/" class="p-category-nav-link">The Philips Sonicare Difference</a>
                    </li>
                    <li class="p-category-nav-item">
                        <a href="/c-m/consumenten-ondersteuning" class="p-category-nav-link">Toothbrushes</a>
                    </li>
                    <li class="p-category-nav-item">
                        <a href="http://www.philips.nl/e/" class="p-category-nav-link">Brush Heads</a>
                    </li>
                    <li class="p-category-nav-item">
                        <a href="http://www.promotion.philips.com/nl/nl/" class="p-category-nav-link">Regimen</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
</div>
