<div class="intro">
    <div class="intro-image">
        <img src="/content/images/intro-bg.jpg" alt="" />
    </div>

    <div class="intro-cell">
        <div class="intro-container">
            <div class="intro-content">
                <h1 class="title">For <strong>healthy teeth</strong> and a white smile</h1>
                <p class="intro-content-text">To help you take good care of your teeth, we’ve developed a range of electrical toothbrushes equipped with Philips’ unique Sonicare technology. These brushes drive fluids between your teeth and along the gum line for healthy teeth and a white smile.</p>
            </div>
        </div>
    </div>
</div>
