<?php
$version = '20140922-1';
$country = 'global';
$language = 'en';
?>
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <title>Philips Sonicare</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1, minimal-ui">
    <meta name="PHILIPS.METRICS.DIVISION" content="CP"/>
    <meta name="PHILIPS.METRICS.COUNTRY" content="<?php echo $country; ?>"/>
    <meta name="PHILIPS.METRICS.LANGUAGE" content="<?php echo $language; ?>"/>
    <meta name="PHILIPS.METRICS.SECTION" content="brush_head_subscription"/>
    <meta name="PHILIPS.METRICS.MICROSITEID" content="S10383"/>
    <meta name="PHILIPS.METRICS.PAGENAME" content="homepage"/>

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <link rel="icon" href="/content/images/favicon.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/content/images/favicon-hd.png">

    <link rel="stylesheet" href="/content/css/app.css?<?php echo $version; ?>">

    <script src="/content/js/modernizr.js?<?php echo $version; ?>"></script>

    <script>
        // (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        //     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        //     m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        // })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        //
        // ga('create', 'UA-54851472-1', 'auto');
        // ga('require', 'displayfeatures');
        // ga('send', 'pageview');
    </script>
</head>
<body>
    <?php include(__DIR__ . '/../header.phtml'); ?>
    <?php include(__DIR__ . '/../intro.phtml'); ?>
    <?php include(__DIR__ . '/../education.phtml'); ?>
    <?php include(__DIR__ . '/../brushSelection.phtml'); ?>

    <?php include(__DIR__ . '/../footer.phtml'); ?>

    <script type="text/javascript" src="//www.crsc.philips.com/crsc/scripts/s_code_philipsglobal.js"></script>

    <script src="/content/js/app.js?<?php echo $version; ?>"></script>
</body>
</html>
