<?php $version = "20140922-1"; ?>
<!DOCTYPE html>

<html class="no-js" lang="nl">
<head>
    <title>Philips Sonicare</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1, minimal-ui">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <link rel="icon" href="/content/images/favicon.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/content/images/favicon-hd.png">

    <link rel="stylesheet" href="/content/css/app.css?<?php echo $version; ?>">

    <script src="/content/js/modernizr.js?<?php echo $version; ?>"></script>

    <script>
        // (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        //     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        //     m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        // })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        //
        // ga('create', 'UA-54851472-1', 'auto');
        // ga('require', 'displayfeatures');
        // ga('send', 'pageview');
    </script>
</head>
<body>
    <?php include(__DIR__ . '/../header.phtml'); ?>
    <?php include(__DIR__ . '/../intro.phtml'); ?>
    <?php include(__DIR__ . '/../education.phtml'); ?>
    <?php

    echo "<pre>";
    print_r($brushes);
    echo "</pre>";


    foreach($brushes as $brush) : ?>
    <div id="<?php echo $brush->id ?>" class="brush" style="background-image: url('<?php echo $brush->image ?>')">
        <div class="name"><?php echo $brush->name ?></div>
    </div>
    <?php endforeach; ?>

    <?php foreach($brushes as $brush) : ?>
        <div id="brushHeads_<?php echo $brush->id ?>" class="brushHeadList">
            <?php foreach($brush->compatibleBrushHeads as $brushhead) : ?>
                <div id="<?php echo $brushhead->id ?>" class="brushhead" style="background-image: url('<?php echo $brushhead->image ?>')">
                    <?php if($brushhead->isStandard) : ?>
                        <div class="standardRibbon"></div>
                    <?php endif; ?>
                    <div class="key"><?php echo $brushhead->key ?></div>
                    <div class="name"><?php echo $brushhead->name ?></div>
                    <div class="description"><?php echo $brushhead->description ?></div>

                    <div class="brushPacks">
                        <?php foreach($brushhead->brushPacks as $brushPack) : ?>
                            <div class="brushpack" id="<?php echo $brushPack->id ?>">
                                <div class="numbrushes">X <?php echo $brushPack->numBrushes ?></div>
                                <div class="price"><?php echo $brushPack->price ?>&euro;</div>

                                <div class="retailers">
                                    <?php foreach($brushPack->retailers as $retailer) : ?>
                                        <div class="retailer" id="<?php echo $retailer->id ?>">
                                            <div class="name"><?php echo $retailer->name ?></div>
                                            <a href="<?php echo $retailer->website ?>">
                                                <img src="<?php echo $retailer->logo ?>" />
                                            </a>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>

                </div>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>

    <?php include(__DIR__ . '/../footer.phtml'); ?>

    <!--<script src="/content/js/app.js?<?php echo $version; ?>"></script>-->
</body>
</html>
